steps:
- args:
  - gcloud
  - functions
  - deploy
  - - connector_${_FUNCTION_NAME}
  - --service-account cloud-functions-${_SERVICE_USER}@${_ENV}-epbp.iam.gserviceaccount.com
  - --source=.
  - --trigger-topic connector_${_FUNCTION_NAME}
  - --runtime python39
  - --memory ${_MEMORY}
  - --timeout ${_TIMEOUT}
  - --region ${_REGION}
  - --no-allow-unauthenticated
  - --set-env-vars PROJECT=${_ENV}-epbp
  - --ingress-settings=${_INGRESS}
  - --project ${_ENV}-epbp
  - --entry-point start_${_FUNCTION_NAME}_connector
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  waitFor:
  - '-'
substitutions:
  _ENV: production
  _FUNCTION_NAME: openweather
  _INGRESS: internal-and-gclb
  _MEMORY: 4096MB
  _REGION: us-east4
  _SERVICE_USER: openweather
